services:
  t430-runner:
    image: ghcr.io/rpdevs-vault/runner-linux-builder:latest
    container_name: t430-runner
    restart: always
    environment:
      - GH_OWNER=RPDevs-Builds
      - GH_TOKEN=${GH_PAT}
      - RUNNER_NAME=t430-runner-01
      - RUNNER_LABELS=self-hosted,Linux,X64,lightweight,t430
      - CCACHE_DIR=/mnt/ccache
    volumes:
      - /mnt/data/github_runners/work/t430-runner:/home/runner/_work
      - /mnt/sharedroot/github_runners/shared:/home/runner/shared
      - /mnt/sharedroot/github_runners/T430:/home/runner/outputs
      - /mnt/sharedroot/data/apt-cache:/var/cache/apt/archives
      - /mnt/sharedroot/ccache:/mnt/ccache
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6G
